ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS builder

ARG REPO_URL
ARG BRANCH
ARG PACKAGE_NAME
ARG CUDA_ARCH
ARG COMMIT_HASH

WORKDIR ${ROS_WS}/src
RUN if [ -n "${COMMIT_HASH}" ]; then \
        git clone --recursive ${REPO_URL} ${PACKAGE_NAME} && \
        cd ${PACKAGE_NAME} && \
        git checkout ${COMMIT_HASH}; \
    else \
        git clone --recursive --depth 1 -b ${BRANCH} ${REPO_URL} ${PACKAGE_NAME}; \
    fi

# Установка зависимостей через rosdep.
RUN apt-get update && \
    rosdep install --from-paths ${ROS_WS}/src -i -y --rosdistro humble \
    --skip-keys=libpcl-all-dev --skip-keys=python3-pcl

# Сборка пакета с флагами CUDA.
WORKDIR ${ROS_WS}
RUN /bin/bash -c "source /opt/ros/humble/setup.bash && \
    colcon build \
        --packages-select ${PACKAGE_NAME} \
        --cmake-args \
            -DCUDA_ARCH=${CUDA_ARCH} \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        --symlink-install"

FROM ${BASE_IMAGE} AS final

COPY --from=builder ${ROS_WS}/install ${ROS_WS}/install
COPY --from=builder ${ROS_WS}/src ${ROS_WS}/src

RUN echo "source /opt/ros/humble/setup.bash && source ${ROS_WS}/install/setup.bash" >> /root/.bashrc

WORKDIR ${ROS_WS}
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["/bin/bash"]
